project_name: "Biblioteca Escolar"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Needs Paulo", "Blocked", "Done", "On Staging", "Live on Prod"]
labels: []
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: false
default_port: 6422
remote_operations: false
auto_commit: false
filesystem_only: false
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
